### ISSUE TITLE
README link issue

### ISSUE THREAD

**Issue by kingspp** [dlizarra/spring-boot-react-webpack-starter#2]
Hi, the link for redux is redirecting for [redux framework for wordpress](http://demo.redux.io/). I feel the redux that front-end react developer uses is different.

http://redux.js.org/
https://github.com/reactjs/react-redux
http://redux.js.org/docs/basics/UsageWithReact.html
https://github.com/reactjs/redux

**Comment by dlizarra** [comment]
Fixed.
Indeed, that was a mistake. Thanks for noticing @kingspp!
